# Generated by Django 4.0.4 on 2022-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshop', '0003_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='send_now',
            field=models.BooleanField(default=True, verbose_name='Отправить email всем покупателям'),
        ),
    ]
